version: 2
updates:
  - package-ecosystem: github-actions
    schedule:
      interval: weekly
      day: friday
      time: '00:00'
    allow:
      - dependency-type: direct
    commit-message:
      prefix: 'chore: '
      include: scope
    labels:
      - Dependencies
    directory: /
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: '00:00'
    allow:
      - dependency-type: direct
    commit-message:
      prefix: 'chore: '
      include: scope
    labels:
      - Dependencies
    versioning-strategy: increase
